services:
  - type: web
    name: damascino-restaurant
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan storage:link
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: APP_NAME
        value: Restaurant
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://damascino-restaurant.onrender.com
      - key: APP_KEY
        generateValue: true
      - key: ASSET_URL
        value: https://damascino-restaurant.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: damascino_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: damascino_db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: damascino_db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: damascino_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: damascino_db
          property: password
    healthCheckPath: /
    disk:
      name: sqlite 
      mountPath: /opt/render/project/src/storage/
      sizeGB: 1

databases:
  - name: damascino_db
    ipAllowList: [] 