services:
  - type: web
    name: damascino-restaurant
    env: php
    buildCommand: |
      curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan storage:link
      chmod -R 777 storage bootstrap/cache
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_NAME
        value: Restaurant
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://damascino-restaurant.onrender.com
      - key: APP_KEY
        generateValue: true
      - key: ASSET_URL
        value: https://damascino-restaurant.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: damascino_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: damascino_db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: damascino_db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: damascino_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: damascino_db
          property: password
    autoDeploy: false
    healthCheckPath: /
    buildFilter:
      paths:
        - app/**/*.php
        - bootstrap/**/*.php
        - config/**/*.php
        - database/**/*.php
        - public/**/*
        - resources/**/*.php
        - routes/**/*.php
        - composer.*

databases:
  - name: damascino_db
    plan: free
    ipAllowList: [] 